//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eomat.ViewModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eveMarketOrdersEntities : DbContext
    {
        public eveMarketOrdersEntities()
            : base("name=eveMarketOrdersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<invTypes> invTypes { get; set; }
        public virtual DbSet<mapRegions> mapRegions { get; set; }
        public virtual DbSet<mapSolarSystems> mapSolarSystems { get; set; }
        public virtual DbSet<staStations> staStations { get; set; }
        public virtual DbSet<invMarketGroups> invMarketGroups { get; set; }
    }
}
