//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eomat.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class invMetaTypes
    {
        public long typeID { get; set; }
        public Nullable<long> parentTypeID { get; set; }
        public Nullable<long> metaGroupID { get; set; }
    }
}
