//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eomat.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class invTypes
    {
        public long typeID { get; set; }
        public Nullable<long> groupID { get; set; }
        public string typeName { get; set; }
        public string description { get; set; }
        public Nullable<double> mass { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> capacity { get; set; }
        public Nullable<long> portionSize { get; set; }
        public Nullable<long> raceID { get; set; }
        public Nullable<decimal> basePrice { get; set; }
        public Nullable<long> published { get; set; }
        public Nullable<long> marketGroupID { get; set; }
        public Nullable<long> graphicID { get; set; }
        public Nullable<long> iconID { get; set; }
        public Nullable<decimal> radius { get; set; }
        public Nullable<long> soundID { get; set; }
    }
}
