//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eomat.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class staStations
    {
        public long stationID { get; set; }
        public Nullable<long> security { get; set; }
        public Nullable<double> dockingCostPerVolume { get; set; }
        public Nullable<double> maxShipVolumeDockable { get; set; }
        public Nullable<long> officeRentalCost { get; set; }
        public Nullable<long> operationID { get; set; }
        public Nullable<long> stationTypeID { get; set; }
        public Nullable<long> corporationID { get; set; }
        public Nullable<long> solarSystemID { get; set; }
        public Nullable<long> constellationID { get; set; }
        public Nullable<long> regionID { get; set; }
        public string stationName { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public Nullable<double> z { get; set; }
        public Nullable<double> reprocessingEfficiency { get; set; }
        public Nullable<double> reprocessingStationsTake { get; set; }
        public Nullable<long> reprocessingHangarFlag { get; set; }
    }
}
